# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ahmed Bensaid
title: Senior Data Analyst
email: a_bensaid@hotmail.com
website: www.github.com/abensaid

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  abensaid
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: abensaid
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-7760-8132
#google_scholar_id: L96iAzEAAAAJ

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=L96iAzEAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/abensaid.png
about_content: | # this will include new lines to allow paragraphs
 As a computer scientist with expertise in artificial intelligence, data analytics, I have a strong foundation in statistical methods, machine learning and data analytics. 
 I am skilled in conducting rigorous research to uncover insights and drive decision-making. My expertise lies in using data to answer complex questions and develop new theories.
 I have a proven track record in teaching and success in publishing research findings in academic journals and presenting at conferences along with
 securing research funds. I am proficient in a variety of programming languages, machine learning tools, and have experience working with large, complex datasets. I also have experience in teaching
 at undergraduate level. I am looking for a challenging and dynamic role in academia where I can utilize my skills and continue to grow.

content:
  - title: Resear Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Speculating Student Performance and Satisfaction in Online Learning During a Pandemic
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The objective is to develop a data-driven approach to predict student outcome
          (fail/pass) in online learning. In addition, this proposal aims at investigating factors that affect
          student satisfaction given the particularity of the learning setting. The addressed challenges
          are of paramount importance for an educational-minded country like Qatar. Indeed, since the
          outbreak of COVID-19, Qatar University and several other educational institutions in Qatar
          have opted for online learning to ensure the continuation of the education process. Hence,
          the research questions this research proposal raises, add significant value to the educational
          system that Qatar aims at equipping the citizens with to achieve their aspirations and to meet
          the needs of Qatar’s society.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
