# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ahmed Bensaid
title: Senior Data Analyst
email: a_bensaid@hotmail.com
website: www.github.com/abensaid

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  abensaid
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: abensaid
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-7760-8132
#google_scholar_id: L96iAzEAAAAJ

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=L96iAzEAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/abensaid.png
about_content: | # this will include new lines to allow paragraphs
As a computer scientist specializing in artificial intelligence and data analytics, I possess deep knowledge in statistical methods and machine learning. 
I excel at rigorous research, deriving insights for decision-making, and formulating novel theories. 
With a proven record in academic publishing, presenting at conferences, and securing research funds, I am adept at multiple programming languages and handling complex datasets. 
Having taught at the undergraduate level, I seek a dynamic academic role where I can further apply and expand my expertise.
content:
  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Speculating Student Performance and Satisfaction in Online Learning During a Pandemic
        description: | # this will include new lines to allow paragraphs
          The goal is to devise a data-driven method to predict student outcomes (fail/pass) in online learning and explore factors influencing student satisfaction in this context. 
          Given Qatar's emphasis on education and the shift to online learning during the COVID-19 pandemic by institutions like Qatar University, this research is crucial. 
          It addresses vital questions, enhancing Qatar's educational system to fulfill societal needs and student aspirations.
      - layout: top-middle    
        title: "COVID-19 outbreak prediction and assessment of prevention policies: a data science approach"
        description: 
          In this project, we leveraged data science to deeply understand the COVID-19 outbreak. 
          Analyzing factors like national lockdowns, school closures, and social distancing, we aim to train a deep learning model using daily case numbers to predict future cases globally, regionally, and nationally.   
      - layout: top-middle
        title: "Arabic Troll account: Exploratory data Analysis"
        description: 
          We analyzed a new dataset from Twitter containing over 98 million tweets from 5,000+ troll accounts. 
          Using big data tools like Dask and Apache Spark, we explored the behaviors, followers, followings, and strategies of these troll accounts on Twitter.
      - layout: top-middle
        title: Cybersecurity for Industrial Control System
        description:
          Cyberwarfare and cybercrime are increasingly targeting ICSs due to their critical role in national security. 
          This project aims to create an early intrusion detection and mitigation solution for ICSs using big data analytics and machine learning. 
          We specifically study a Water Treatment Facility, examining ICS data at network and physical levels.
      - layout: top-middle
        title: Spatio-temporal composition of Sensor crowdsourced services
        description: 
          We developed a platform for individuals to share their WiFi during the FIFA World Cup 2022, enhancing internet coverage. 
          Using time series analysis, Gramian Angular Field, and a ResNet model in Tensorflow-Keras, we predicted service availability by location and time. 
          Additionally, we detected convoys from commuter trajectories using cluster analysis.
      - layout: top-middle
        title: "Analysis of Stock market of emerging countries: Qatar stock as a case study"
        description: 
          We analyzed the stock market of emerging countries, focusing on Qatar. Using advanced deep learning, we explored how company indexes in sectors like Banking, Insurance, and Oil & Gas react to global market indicators such as the S&P, Nikkei, and oil prices.     
      - layout: top-middle
        title: "QHCN: Towards Reliable and Efficient IoT mHealth System with Multimodal Processing and Communications for Effective Remote Patient Diagnosis"
        description: 
          We created a Mobile HealthCare Network platform to efficiently collect vital signs (e.g., EEG, ECG) from devices and send them to a remote server. 
          We employed a multimodal stacked autoencoder in Tensorflow-Keras for data compression across multiple modalities.  
      - layout: top-middle
        title: "Advances in biometrics via narrowband multispectral imaging"
        description:
          We developed a face recognition system using narrowband multispectral images. 
          The project involved enhancing sensory data by denoising and segmenting these images. 
          We utilized various denoising methods tailored for spectral data in MATLAB and performed multispectral image segmentation using cluster analysis.        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      1- LIME: Long-Term Forecasting Model for Desalination Membrane Fouling to Estimate the Remaining Useful Life of Membrane, S. Eltanbouly, A. Erradi, A. Tantawy, A. Ben Said, K. Shaban, H. Qiblawey, International Conference on Industrial, Engineering and Other Applications of Applied Intelligent Systems, 3-14, 2023
      
      2: Performance prediction in online academic course: a deep learning approach with time series imaging, A. Ben Said, A. G Abdelsalam, K. Hazaa, **Multimedia Tools and Applications (IF 3.6)**, 2023 (Minor Revision)
      
      3: Machine learning for prediction of the uniaxial compressive strength within carbonate rocks, M. Abdelhedi, R. Jabbar, A. Ben Said, N. Fetais, C. Abbes, **Earth Science Informatics (IF 2.8)**, 16, pp. 1473–1487, 2023
      
      4: Optimal Resource Management for Hierarchical Federated Learning over HetNets with Wireless Energy Transfer, R. Hamdi, A. Ben Said, E. Baccour, A. Erbad, A. Mohamed, M. Hamdi, M Guizani, **IEEE Internet of Things Journal (IF 10.6)**, 2023
      
      5: Determinants of poor academic performance among undergraduate students—A systematic literature review, R. A. Naji Al-Tameemi, C. Johnson, R. Gitay, A. G Abdelsalam, K. Hazaa, A. Ben Said, M. H. Romanowski, **International Journal of Educational Research Open**, pp 100232, 2023

      6: Student support in higher education: campus service utilization, impact, and challenges, C. Johnson, R. Gitay, A. G Abdelsalam, A. Ben Said, R. Ismail, R. A. Naji Al-Tameemi, M. H. Romanowski, B. Al Fakih, K. Hazaa, **Heliyon (IF 4)**, pp e12559, 2022

      7: Causes of Undergraduate Students’ Underachievement in a Gulf Cooperation Council Country (GCC) University, C Johnson, R. Gitay, K. Hazaa, A. G Abdelsalam, R. I. Mohamed, A. Ben Said, R. A. Naji Al-Tameemi, M. H. Romanowski, **SAGE Open (IF 2.0)**, pp. 21582440221079847, 2022
            
      8: Factors Affecting University Image among Graduate Alumni: A Case Study of Qatar University, K. Hazaa, A. G. Abdelsalam, M. D. Mollazehi, R. I. Mohamed, M. A. Ahmed, R. A. AlTameemi, A. Ben Said, C. Johnson, M. H. Romanowski, **Heliyon (IF 4)**, pp e09668, 2022

      9: Blockchain Technology for Intelligent Transportation Systems: A Systematic Literature Review, R. Jabbar, E. Dhib, A. Ben Said, M. Krichen, N. Fetais, E. Zaidan, K. Barkaoui, ***IEEE Access (IF 3.9)**, vol. 10, pp 20995-21031, 2022

      10: R. Hamdi, A. Ben Said, A. Erbed, A. Mohamed, M. Hamdi, M. Guizani, Hierarchical Federated Learning over HetNets enabled by Wireless Energy Transfer, IEEE Global Communications Conference (GLOBECOM), pp 1-6, 2021

      11: R. Hamdi, M. Chen, A. Ben Said, M. Qaraqe, H. V. Poor, Federated Learning over Energy Harvesting Wireless Networks, **IEEE Internet of Things Journal (IF 10.6)**, pp 92-103, 2021

      12: A. Ben Said, A. Erradi, H. Aly, A. Mohamed, Predicting COVID-19 cases using Bidirectional LSTM on multivariate time series, **Environmental Science and Pollution Research (IF 5.8)**, pp 1-10, 2021

      13: A. Ben Said, A. Erradi, Spatiotemporal tensor completion for improved urban traffic imputation, **IEEE Transactions on Intelligent Transportation Systems (IF 8.5)**, pp 6836-6849, 2021
      
      14: S. Ayadi, A. Ben Said, R. Jabbar, C. Aloulou, A Chaboouh, A. Achballah, Dairy Cow rumination detection: A deep learning approach, DICES-N Conference, pp 123-139, 2020

      15:  A. Ben Said, A. Erradi, H. Aly, A. Mohamed, Predicting COVID-19 cases using Bidirectional LSTM on multivariate time series, arXiv:2009.123255

      16: A. Ben Said, A. Erradi, A probabilistic approach for maximizing travel journey WiFi coverage using mobile crowdsourced services, **IEEE Access (IF 3.9)**, pp 82297-82307, 2019
      
      17: A. Ben Said, A. Erradi, A. Ghari Neait and A. Bouguettaya, A Deep Learning Spatiotemporal Prediction Framework for Mobile Crowdsourced Services, **Mobile Networks andApplications (IF 3.8)**, pp 1-14, 2018
      
      18: A. Ben Said, R. Hadjidj and S. Foufou, Total Variation for Image Denoising Based on a Novel Smart Edge Detector: An Application to Medical Images, **Journal of Mathematical Imaging and Vision (IF 2)**, pp 1-16, 2018
      
      21: A. Ben Said, A. G Abdelsalam, K. Hazaa, Factors affecting student satisfaction towards online teaching: a machine learning approach, Digital Economy, Business Analytics, and Big Data Analytics Applications Conference, pp 309-318, 2022

      22: R. Hamdi, M. Chen, A. Ben Said, M. Qaraqe, V. Poor, User Scheduling in Federated Learning over Energy Harvesting Wireless Networks, 2021 IEEE Global Communications Conference (GLOBECOM), pp 1-6, 2021

      23: A. Ben Said, A. Erradi, Multiview topological data analysis for crowdsourced service supplydemand gap prediction, 2020 International Wireless Communications and Mobile Computing (IWCMC), pp 1818-1823, 2020
      
      24: A. Ben Said, S. Foufou and R. Hadjidj, Cluster validity index based on jeffrey divergence, **Pattern Analysis and Applications (IF 3.9)**, pp 1-11, 2015.
      
      25: S. Alhazbi, A. Ben Said, A. Al-Maadid, Using Deep Learning to Predict Stock Movements Direction in Emerging Markets: The Case of Qatar Stock Exchange, IEEE International Conference on Informatics, IoT, and Enabling Technologies, 2020
      
      26: A. Ben Said, A. Erradi, Deep-Gap: A a deep learning framework for forecasting crowdsourcing supply-demand gap based on imaging time series and residual learning, CloudCom 2019

      27: A. Ben Said, A. Erradi, A. Ghari Neait and A. Bouguettaya, Mobile crowdsourced sensors selection for journey services, International Conference on Service-Oriented Computing, pp 463-477, 2019

      28: A. Ben Said, A. Mohamed, T. Elfouly, K. Abualsaud and K. Harras, Deep learning and low rank dictionary model for mHealth data classification, 14th International Wireless Communications & Mobile Computing Conference (IWCMC), pp 358-363, 2018.

      29: A. Ben Said, A. Mohamed and T. Elfouly, Deep learning approach for EEG compression in mHealth system, 13th Wireless Communications and Mobile Computing Conference (IWCMC), pp 1508-1512, 2017.
      
      30: A. Ben Said, A. Mohamed, T. Elfouly, K. Harras and J. Wang, Multimodal deep learning approach for joint EEG-EMG data compression and classification, IEEE Wireless Communications and Networking Conference (WCNC), pp 1-6, 2017
      
      31: A. Ben Said, R. Hadjidj, S. Foufou and M. Abidi, Edge guided total variation for image denoising, 51st Annual Conference on Information Sciences and Systems (CISS), pp 1-6, 2017.

      32:  A. Ben Said and S. Foufou, Modified total variation regularization using fuzzy complement for image denoising, Iternational Conference on mage and Vision Computing New Zealand (IVCNZ), pp 1-6, 2016.

      33: A. Ben Said and S. Foufou, Multispectral Image Denoising Using Optimized Vector NLM Filter, Pacific-Rim Symposium on Image and Video Technology, pp 309-320, 2015

      34: A. Ben Said, S. Foufou and R. Hadjidj, Vector anisotropic filter for multispectral image denoising, The International Conference on Quality Control by Artificial Vision, pp 95340N-95340N-8, 2015.

      35: A. Ben Said, S. Foufou and M. Abidi, Cluster validity index based on n-sphere, EEE/ACS 11th International Conference on Computer Systems and Applications (AICCSA), pp 144-147, 2014
    
      36: A. Ben Said, R. Hadjidj and S. Foufou, Gravitational weighted fuzzy c-means with application on multispectral image segmentation, 4th International Conference on Image Processing Theory, Tools and Applications (IPTA), pp 1-5, 2014.

      37:  A. Ben Said, S. Foufou and M. Abidi, A fcm and surf based algorithm for segmentation of multispectral face images, International Conference on ignal-Image Technology Internet-Based Systems (SITIS), pp 65-70, 2013

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-seo-tag
